name: Build and deploy package

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOTNET_CONFIGURATION: Release

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration ${{ env.DOTNET_CONFIGURATION }} --no-restore

      - name: Run tests
        run: dotnet test --configuration ${{ env.DOTNET_CONFIGURATION }} --no-build --verbosity normal

      - name: Create the Package
        run: dotnet pack --configuration ${{ env.DOTNET_CONFIGURATION }} --no-build --output ./nupkg

      - name: Publish to NuGet
        run: dotnet nuget push "./nupkg/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
